// Centralized UI strings. Single-language app (Chinese) — see project_context.md.
// Task-type labels live in taskLabels.ts (keyed by the enum); everything else is here.
export const t = {
  nav: {
    thisWeek: '本周计划',
    management: '管理',
  },
  plan: {
    title: '本周计划',
    loading: '加载中…',
    empty: '本周暂无任务',
    allAssignees: '全部成员',
    allProperties: '全部房源',
    prevWeek: '上一周',
    nextWeek: '下一周',
    pickWeek: '选择周',
    markDone: '标记为完成',
    markUndone: '标记为未完成',
    manual: '手动',
  },
  admin: {
    sections: { bookings: '预订', takeovers: '代管', properties: '房源' },
    allProperties: '全部房源',
    close: '关闭',
    selectBooking: '请选择一个预订进行编辑',
    // booking detail
    guestName: '房客姓名',
    guestNamePh: '房客姓名',
    lockCode: '门锁密码',
    lockCodePh: '例如 482736',
    notes: '备注',
    notesPh: '本次入住的备注…',
    save: '保存',
    saving: '保存中…',
    saved: '已保存 ✓',
    // tasks
    tasksTitle: '任务',
    manual: '手动',
    addNote: '+ 备注',
    editNote: '编辑备注',
    notePh: '该任务的备注…',
    saveNote: '保存备注',
    cancel: '取消',
    // takeovers
    takeoverTitle: '代管时间段',
    fromPerson: '原负责人…',
    toPerson: '接管人…',
    dateTo: '至',
    add: '添加',
    remove: '移除',
    addTakeover: '+ 添加代管',
    // properties
    propName: '名称',
    namePh: '例如 海景小屋',
    icalUrl: 'iCal 链接',
    icalPh: 'https://www.airbnb.com/calendar/ical/…',
    checkinTime: '入住时间',
    checkoutTime: '退房时间',
    defaultPasscode: '默认密码（Eufy 管理员）',
    passcodePh: '例如 135790',
    syncIcal: '同步 iCal',
    syncing: '同步中…',
    addProperty: '+ 添加房源',
    addPropertyTitle: '添加房源',
    addPropertyBtn: '添加房源',
  },
};
